### ISSUE TITLE
OAS crashes due to unability to handle models containing enums

### ISSUE THREAD

**Issue by posiczko** [a-chacon/oas_rails#67]
OAS is crashing when models contain enums.

```
Started GET "/docs.json" for 127.0.0.1 at 2024-12-29 10:08:01 -0700
Processing by OasRails::OasRailsController#index as JSON
Started GET "/favicon.ico" for 127.0.0.1 at 2024-12-29 10:08:01 -0700
Completed 500 Internal Server Error in 210ms (ActiveRecord: 5.4ms (0 queries, 0 cached) | GC: 31.0ms)


  
ArgumentError (Unsupported type: enum):
  
model-to-schema (0.1.2) lib/esquema/type_caster.rb:49:in `cast'
model-to-schema (0.1.2) lib/esquema/property.rb:86:in `build_default'
model-to-schema (0.1.2) lib/esquema/property.rb:64:in `block in as_json'
model-to-schema (0.1.2) lib/esquema/property.rb:63:in `each'
model-to-schema (0.1.2) lib/esquema/property.rb:63:in `each_with_object'
model-to-schema (0.1.2) lib/esquema/property.rb:63:in `as_json'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `block in as_json'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `each'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `as_json'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `block in as_json'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `each'
activesupport (8.0.1) lib/active_support/core_ext/object/json.rb:194:in `as_json'
oas_rails (0.8.3) lib/oas_rails/builders/esquema_builder.rb:13:in `build_incoming_schema'
oas_rails (0.8.3) lib/oas_rails/builders/content_builder.rb:38:in `from_model_class'
oas_rails (0.8.3) lib/oas_rails/builders/request_body_builder.rb:34:in `from_model_class'
oas_rails (0.8.3) lib/oas_rails/builders/request_body_builder.rb:57:in `detect_request_body'
oas_rails (0.8.3) lib/oas_rails/builders/request_body_builder.rb:12:in `from_oas_route'
oas_rails (0.8.3) lib/oas_rails/builders/operation_builder.rb:18:in `from_oas_route'
oas_rails (0.8.3) lib/oas_rails/builders/path_item_builder.rb:12:in `block (2 levels) in from_path'
oas_rails (0.8.3) lib/oas_rails/builders/path_item_builder.rb:11:in `each'
oas_rails (0.8.3) lib/oas_rails/builders/path_item_builder.rb:11:in `block in from_path'
oas_rails (0.8.3) lib/oas_rails/builders/path_item_builder.rb:10:in `each'
oas_rails (0.8.3) lib/oas_rails/builders/path_item_builder.rb:10:in `from_path'
oas_rails (0.8.3) lib/oas_rails/spec/paths.rb:14:in `add_path'
oas_rails (0.8.3) lib/oas_rails/spec/specification.rb:25:in `block in build'
oas_rails (0.8.3) lib/oas_rails/spec/specification.rb:24:in `each'
oas_rails (0.8.3) lib/oas_rails/spec/specification.rb:24:in `build'
oas_rails (0.8.3) lib/oas_rails.rb:67:in `build'
oas_rails (0.8.3) app/controllers/oas_rails/oas_rails_controller.rb:10:in `block (2 levels) in index'
actionpack (8.0.1) lib/action_controller/metal/mime_responds.rb:224:in `respond_to'
oas_rails (0.8.3) app/controllers/oas_rails/oas_rails_controller.rb:7:in `index'
actionpack (8.0.1) lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
actionpack (8.0.1) lib/abstract_controller/base.rb:226:in `process_action'
actionpack (8.0.1) lib/action_controller/metal/rendering.rb:193:in `process_action'
...
```

**Comment by a-chacon** [comment]
Hello, thank you for report it. I think I never test that case. I have not much time right now, but I will be looking to solve it.

If you want a quick solution you can try to solve it and send me a PR, I would be happy to review it and release a new version asap.

**Comment by a-chacon** [comment]
HI @posiczko! I was trying to reproduce the error but I cant. Can you give me the steps for reproduce it please? I tested it in a Rails 8.0.2 app with a simple enum in a model backed by a integer column and I tested using the model as a request body and response and dont fail. 

With the logs you share, I can see the problem is in dependency gem. But If I am not able to reproduce it I cant find a solution :( I am gonna try it later, but if you give me more context or steps to reproduce it would be nice

I tested this:
```ruby
  # POST /books
  # @request_body The book to be created [Book]
  # @response The book(200) [Book]
  def create
    @book = Book.new(book_params)

    if @book.save
      render json: @book, status: :created, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

```

Where book model have an enum: 
```ruby
class Book < ApplicationRecord
  belongs_to :user, optional: false

  enum :kind, [ :fiction, :novel ]
end

```

**Comment by a-chacon** [comment]
Apparently the error was produced in the dependency gem `model-to-schema` that was replaced with `easy-talk` here: https://github.com/a-chacon/oas_rails/pull/82

I close it for now.
